name: Update Recent Articles

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-recent-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Pull latest changes
        run: git pull origin main

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        run: node scripts/update-recent-articles.js

      - name: Check if recent-articles.md has changed
        id: check_changes
        run: |
          if git diff --exit-code docs/recent-articles.md; then
            echo "file_changed=false" >> $GITHUB_ENV
          else
            echo "file_changed=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.file_changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add docs/recent-articles.md
          git commit -m "docs: update recent articles"
          git push origin main
