name: Update README

on:
  # issues:
  #   types: [opened, deleted]
  push:
    paths:
      - docs/templates/readme.md

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --production

      - name: Run update-readme script
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        run: bun run scripts/update-readme.ts

      - name: Check if README.md has changed
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "file_changed=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.file_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          GITHUB_USER: tofrankie
          GITHUB_REPO: blog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: update readme"
          git push origin main
